name: MacInside
options:
  bundleIdPrefix: fr.vincentlauriat
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  developmentLanguage: fr

settings:
  base:
    DEVELOPMENT_TEAM: "KFLACS69T9"
    ENABLE_HARDENED_RUNTIME: YES

schemes:
  MacInside:
    build:
      targets:
        MacInside: all
    run:
      config: Debug
    archive:
      config: Release

targets:
  MacInside:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: MacInside
        excludes:
          - "**/*.entitlements"
          - "Info.plist"
    settings:
      base:
        PRODUCT_NAME: MacInside
        PRODUCT_BUNDLE_IDENTIFIER: fr.vincentlauriat.macinside
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: MacInside/MacInside.entitlements
        CODE_SIGN_IDENTITY: "Developer ID Application"
        CODE_SIGN_STYLE: Manual
    info:
      path: MacInside/Info.plist
      properties:
        CFBundleName: MacInside
        CFBundleDisplayName: MacInside
        CFBundleIdentifier: fr.vincentlauriat.macinside
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDevelopmentRegion: fr
        CFBundleLocalizations: [fr, en]
        LSMinimumSystemVersion: "14.0"
        LSApplicationCategoryType: public.app-category.utilities
        LSUIElement: false
        NSHumanReadableCopyright: "© 2026 Vincent Lauriat"
        NSHighResolutionCapable: true
